language: node_js

node_js:
  - node

script: npm run test:coverage && npm run build

#deploy:
#  - provider: npm
#    email: NPM_EMAIL
#    api_key: NPM_API_KEY
#  - provider: releases
#    draft: true
#    edge: true
#    file: dist/*
#    on:
#      all_branches: true
#      tags: true
#    prerelease: true
#    tag_name: v2.0.0-alpha

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3315ee8656f78a47b371
#    on_success: change  # options: [always|never|change] default: always
#    on_failure: always  # options: [always|never|change] default: always
#    on_start: never     # options: [always|never|change] default: always
